name: "Composer Require Checker"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  composer-require-checker:
    name: "Composer Require Checker"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "8.0"
          ini-values: memory_limit=-1

      - uses: "ramsey/composer-install@2.1.0"

      - name: "Install require checker"
        run: "composer require --dev -W maglnet/composer-require-checker"

      - name: "Check"
        run: "vendor/bin/composer-require-checker check"
