name: "Mutation Tests"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  mutation-tests:
    name: "Mutation Tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "7.4"
          ini-values: memory_limit=-1

      - uses: "ramsey/composer-install@2.1.0"

      - name: "Run mutation tests"
        run: "vendor/bin/infection --configuration=infection.json"
