name: "Mutation Tests - Pull Request Annotations"

on:
  pull_request:

jobs:
  mutation-tests:
    name: "Mutation Tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "7.4"
          ini-values: memory_limit=-1

      - uses: "ramsey/composer-install@2.1.0"

      - name: "Run mutation tests"
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          vendor/bin/infection --configuration=infection.json --git-diff-filter=AM --git-diff-base=origin/$GITHUB_BASE_REF --logger-github
